NAME=		avrnotes
TEXSRCS=    flip.tex\
			toolchain.tex \
			avrdude.tex \
			screen.tex \
			udevrule.tex \
			building.tex \
			doctools/latex/mycommands.tex
#BIBTEXSRCS= latex/hydrorefs.bib


include /usr/share/latex-mk/latex.gmk
